/**
 * Dữ liệu mẫu (Mock Data) độc lập cho hệ thống thanh toán VietQR SePay.
 * Tuân thủ Hiến pháp dự án: Tách rời dữ liệu mẫu khỏi giao diện để dễ thay thế bằng API backend.
 */

// Thông tin tài khoản ngân hàng thụ hưởng mặc định
export const DEFAULT_BANK_INFO = {
  bankCode: 'MB',
  bankName: 'MBBank - Ngân hàng TMCP Quân Đội',
  accountNumber: '0987654321',
  accountHolder: 'CONG TY CP CONG NGHE JOBVIET',
};

// Hàm sinh link mã QR chuẩn VietQR
export const generateVietQrUrl = (bankCode, accountNumber, amount, transferContent) => {
  const encodedContent = encodeURIComponent(transferContent);
  return `https://img.vietqr.io/image/${bankCode}-${accountNumber}-compact2.png?amount=${amount}&addInfo=${encodedContent}`;
};

// Danh sách các đơn thanh toán mẫu
export const initialMockOrders = [
  {
    orderId: 'PAY-20261009-001',
    orderType: 'CANDIDATE_TOKEN',
    serviceName: 'Gói 50 Token Ứng viên (Mở khóa CV)',
    userId: 'USR-UV-01',
    userName: 'Nguyễn Văn An',
    userEmail: 'an.nguyen@gmail.com',
    userRole: 'candidate',
    amount: 50000,
    actualAmount: null,
    status: 'PENDING',
    bankCode: DEFAULT_BANK_INFO.bankCode,
    bankName: DEFAULT_BANK_INFO.bankName,
    accountNumber: DEFAULT_BANK_INFO.accountNumber,
    accountHolder: DEFAULT_BANK_INFO.accountHolder,
    transferContent: 'JOBVIET PAY001',
    qrCodeUrl: generateVietQrUrl(
      DEFAULT_BANK_INFO.bankCode,
      DEFAULT_BANK_INFO.accountNumber,
      50000,
      'JOBVIET PAY001'
    ),
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(), // Hết hạn sau 15 phút
  },
  {
    orderId: 'PAY-20261009-002',
    orderType: 'EMPLOYER_PACKAGE',
    serviceName: 'Gói Tuyển Dụng Tiêu Chuẩn (30 ngày)',
    userId: 'USR-NTD-01',
    userName: 'Công ty Công nghệ FPT Software',
    userEmail: 'hr@fpt.com',
    userRole: 'employer',
    amount: 500000,
    actualAmount: null,
    status: 'PENDING',
    bankCode: DEFAULT_BANK_INFO.bankCode,
    bankName: DEFAULT_BANK_INFO.bankName,
    accountNumber: DEFAULT_BANK_INFO.accountNumber,
    accountHolder: DEFAULT_BANK_INFO.accountHolder,
    transferContent: 'JOBVIET PAY002',
    qrCodeUrl: generateVietQrUrl(
      DEFAULT_BANK_INFO.bankCode,
      DEFAULT_BANK_INFO.accountNumber,
      500000,
      'JOBVIET PAY002'
    ),
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
  },
  {
    orderId: 'PAY-20261009-003',
    orderType: 'CANDIDATE_TOKEN',
    serviceName: 'Gói 100 Token Ứng viên (Ưu đãi)',
    userId: 'USR-UV-02',
    userName: 'Trần Thị Mai',
    userEmail: 'mai.tran@gmail.com',
    userRole: 'candidate',
    amount: 100000,
    actualAmount: 100000,
    status: 'SUCCESS',
    bankCode: DEFAULT_BANK_INFO.bankCode,
    bankName: DEFAULT_BANK_INFO.bankName,
    accountNumber: DEFAULT_BANK_INFO.accountNumber,
    accountHolder: DEFAULT_BANK_INFO.accountHolder,
    transferContent: 'JOBVIET PAY003',
    qrCodeUrl: generateVietQrUrl(
      DEFAULT_BANK_INFO.bankCode,
      DEFAULT_BANK_INFO.accountNumber,
      100000,
      'JOBVIET PAY003'
    ),
    createdAt: new Date(Date.now() - 3600 * 1000).toISOString(),
    expiresAt: new Date(Date.now() - 3600 * 1000 + 15 * 60 * 1000).toISOString(),
  },
  {
    orderId: 'PAY-20261009-004',
    orderType: 'EMPLOYER_PACKAGE',
    serviceName: 'Gói Doanh Nghiệp VIP (90 ngày)',
    userId: 'USR-NTD-02',
    userName: 'VNG Corporation',
    userEmail: 'recruitment@vng.com.vn',
    userRole: 'employer',
    amount: 2000000,
    actualAmount: 1500000,
    status: 'WRONG_AMOUNT',
    bankCode: DEFAULT_BANK_INFO.bankCode,
    bankName: DEFAULT_BANK_INFO.bankName,
    accountNumber: DEFAULT_BANK_INFO.accountNumber,
    accountHolder: DEFAULT_BANK_INFO.accountHolder,
    transferContent: 'JOBVIET PAY004',
    qrCodeUrl: generateVietQrUrl(
      DEFAULT_BANK_INFO.bankCode,
      DEFAULT_BANK_INFO.accountNumber,
      2000000,
      'JOBVIET PAY004'
    ),
    createdAt: new Date(Date.now() - 7200 * 1000).toISOString(),
    expiresAt: new Date(Date.now() - 7200 * 1000 + 15 * 60 * 1000).toISOString(),
  },
  {
    orderId: 'PAY-20261009-005',
    orderType: 'CANDIDATE_TOKEN',
    serviceName: 'Gói 20 Token Ứng viên',
    userId: 'USR-UV-03',
    userName: 'Lê Hoàng Nam',
    userEmail: 'nam.le@gmail.com',
    userRole: 'candidate',
    amount: 20000,
    actualAmount: null,
    status: 'EXPIRED',
    bankCode: DEFAULT_BANK_INFO.bankCode,
    bankName: DEFAULT_BANK_INFO.bankName,
    accountNumber: DEFAULT_BANK_INFO.accountNumber,
    accountHolder: DEFAULT_BANK_INFO.accountHolder,
    transferContent: 'JOBVIET PAY005',
    qrCodeUrl: generateVietQrUrl(
      DEFAULT_BANK_INFO.bankCode,
      DEFAULT_BANK_INFO.accountNumber,
      20000,
      'JOBVIET PAY005'
    ),
    createdAt: new Date(Date.now() - 86400 * 1000).toISOString(),
    expiresAt: new Date(Date.now() - 86400 * 1000 + 15 * 60 * 1000).toISOString(),
  },
  {
    orderId: 'PAY-20261009-006',
    orderType: 'EMPLOYER_PACKAGE',
    serviceName: 'Gói Đăng Tin Tuyển Dụng Nhanh',
    userId: 'USR-NTD-03',
    userName: 'Tiki Corporation',
    userEmail: 'jobs@tiki.vn',
    userRole: 'employer',
    amount: 150000,
    actualAmount: null,
    status: 'CANCELLED',
    bankCode: DEFAULT_BANK_INFO.bankCode,
    bankName: DEFAULT_BANK_INFO.bankName,
    accountNumber: DEFAULT_BANK_INFO.accountNumber,
    accountHolder: DEFAULT_BANK_INFO.accountHolder,
    transferContent: 'JOBVIET PAY006',
    qrCodeUrl: generateVietQrUrl(
      DEFAULT_BANK_INFO.bankCode,
      DEFAULT_BANK_INFO.accountNumber,
      150000,
      'JOBVIET PAY006'
    ),
    createdAt: new Date(Date.now() - 172800 * 1000).toISOString(),
    expiresAt: new Date(Date.now() - 172800 * 1000 + 15 * 60 * 1000).toISOString(),
  },
];

// Danh sách các giao dịch đối soát hiển thị cho Quản trị viên
export const initialMockTransactions = [
  {
    transactionId: 'TX-9872134',
    orderId: 'PAY-20261009-003',
    orderType: 'CANDIDATE_TOKEN',
    serviceName: 'Gói 100 Token Ứng viên (Ưu đãi)',
    userName: 'Trần Thị Mai',
    userEmail: 'mai.tran@gmail.com',
    expectedAmount: 100000,
    actualAmount: 100000,
    referenceCode: 'FT26100998124',
    status: 'SUCCESS',
    receivedAt: '2026-10-09T08:05:22Z',
    webhookLogId: 'WH-LOG-003',
  },
  {
    transactionId: 'TX-9872135',
    orderId: 'PAY-20261009-004',
    orderType: 'EMPLOYER_PACKAGE',
    serviceName: 'Gói Doanh Nghiệp VIP (90 ngày)',
    userName: 'VNG Corporation',
    userEmail: 'recruitment@vng.com.vn',
    expectedAmount: 2000000,
    actualAmount: 1500000,
    referenceCode: 'FT26100998125',
    status: 'WRONG_AMOUNT',
    receivedAt: '2026-10-09T07:12:15Z',
    webhookLogId: 'WH-LOG-004',
  },
  {
    transactionId: 'TX-9872136',
    orderId: 'PAY-20261009-001',
    orderType: 'CANDIDATE_TOKEN',
    serviceName: 'Gói 50 Token Ứng viên (Mở khóa CV)',
    userName: 'Nguyễn Văn An',
    userEmail: 'an.nguyen@gmail.com',
    expectedAmount: 50000,
    actualAmount: 0,
    referenceCode: '-',
    status: 'PENDING',
    receivedAt: null,
    webhookLogId: 'WH-LOG-001',
  },
  {
    transactionId: 'TX-9872137',
    orderId: 'PAY-20261009-002',
    orderType: 'EMPLOYER_PACKAGE',
    serviceName: 'Gói Tuyển Dụng Tiêu Chuẩn (30 ngày)',
    userName: 'Công ty Công nghệ FPT Software',
    userEmail: 'hr@fpt.com',
    expectedAmount: 500000,
    actualAmount: 0,
    referenceCode: '-',
    status: 'PENDING',
    receivedAt: null,
    webhookLogId: 'WH-LOG-002',
  },
  {
    transactionId: 'TX-9872138',
    orderId: 'PAY-20261009-005',
    orderType: 'CANDIDATE_TOKEN',
    serviceName: 'Gói 20 Token Ứng viên',
    userName: 'Lê Hoàng Nam',
    userEmail: 'nam.le@gmail.com',
    expectedAmount: 20000,
    actualAmount: 0,
    referenceCode: '-',
    status: 'EXPIRED',
    receivedAt: null,
    webhookLogId: 'WH-LOG-005',
  },
  {
    transactionId: 'TX-9872139',
    orderId: 'PAY-20261009-006',
    orderType: 'EMPLOYER_PACKAGE',
    serviceName: 'Gói Đăng Tin Tuyển Dụng Nhanh',
    userName: 'Tiki Corporation',
    userEmail: 'jobs@tiki.vn',
    expectedAmount: 150000,
    actualAmount: 0,
    referenceCode: '-',
    status: 'CANCELLED',
    receivedAt: null,
    webhookLogId: 'WH-LOG-006',
  },
];

// Dữ liệu Webhook log mẫu mô phỏng từ cổng SePay
export const initialMockWebhookLogs = {
  'WH-LOG-003': {
    id: 'WH-LOG-003',
    transactionId: 'TX-9872134',
    orderCode: 'PAY-20261009-003',
    gateway: 'SePay - MBBank',
    receivedAt: '2026-10-09T08:05:22Z',
    rawPayload: {
      id: 9872134,
      gateway: 'MBBank',
      transactionDate: '2026-10-09 08:05:22',
      accountNumber: '0987654321',
      code: null,
      content: 'JOBVIET PAY003 chuyen khoan nap token',
      transferType: 'in',
      transferAmount: 100000,
      accumulated: 15450000,
      subAccount: null,
      referenceCode: 'FT26100998124',
      description: 'Chuyển khoản thành công đơn hàng PAY-20261009-003',
    },
  },
  'WH-LOG-004': {
    id: 'WH-LOG-004',
    transactionId: 'TX-9872135',
    orderCode: 'PAY-20261009-004',
    gateway: 'SePay - MBBank',
    receivedAt: '2026-10-09T07:12:15Z',
    rawPayload: {
      id: 9872135,
      gateway: 'MBBank',
      transactionDate: '2026-10-09 07:12:15',
      accountNumber: '0987654321',
      code: null,
      content: 'JOBVIET PAY004 mua goi VIP',
      transferType: 'in',
      transferAmount: 1500000,
      accumulated: 15350000,
      subAccount: null,
      referenceCode: 'FT26100998125',
      description: 'Sai số tiền: Cần 2.000.000đ nhưng nhận 1.500.000đ',
    },
  },
  'WH-LOG-001': {
    id: 'WH-LOG-001',
    transactionId: 'TX-9872136',
    orderCode: 'PAY-20261009-001',
    gateway: 'SePay - MBBank',
    receivedAt: null,
    rawPayload: {
      status: 'WAITING_FOR_PAYMENT',
      message: 'Chưa nhận được giao dịch chuyển khoản từ ngân hàng',
    },
  },
  'WH-LOG-002': {
    id: 'WH-LOG-002',
    transactionId: 'TX-9872137',
    orderCode: 'PAY-20261009-002',
    gateway: 'SePay - MBBank',
    receivedAt: null,
    rawPayload: {
      status: 'WAITING_FOR_PAYMENT',
      message: 'Chưa nhận được giao dịch chuyển khoản từ ngân hàng',
    },
  },
  'WH-LOG-005': {
    id: 'WH-LOG-005',
    transactionId: 'TX-9872138',
    orderCode: 'PAY-20261009-005',
    gateway: 'SePay - MBBank',
    receivedAt: null,
    rawPayload: {
      status: 'TRANSACTION_EXPIRED',
      message: 'Đơn hàng quá thời hạn 15 phút, hệ thống đã đóng theo dõi',
    },
  },
  'WH-LOG-006': {
    id: 'WH-LOG-006',
    transactionId: 'TX-9872139',
    orderCode: 'PAY-20261009-006',
    gateway: 'SePay - MBBank',
    receivedAt: null,
    rawPayload: {
      status: 'ORDER_CANCELLED',
      message: 'Người dùng chủ động hủy giao dịch trên hệ thống',
    },
  },
};
